services:
  mongo:
    container_name: mongo-cart
    image: mongo:latest
    restart: always
    ports:
      - "27020:27017"
      
  goapp:
    build: .
    container_name: goapp-cart
    ports:
      - "8085:8085"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/

