services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
      
  goapp:
    build: .
    container_name: goapp
    ports:
      - "8085:8085"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo

