services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27021:27017"
      
  goapp:
    build: .
    container_name: goapps
    ports:
      - "8085:8085"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/

