services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27019:27019"
      
  goapp:
    build: .
    container_name: goapp
    ports:
      - "8082:8082"
    depends_on:
      - mongo
