services:
  mongo:
    container_name: mongo-order
    image: mongo:latest
    restart: always
    ports:
      - "27022:27017"
      
  goapp:
    build: .
    container_name: goapp-order
    ports:
      - "8083:8083"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
