services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27019:27017"
      
  goapp:
    build: .
    container_name: goapp
    ports:
      - "8086:8086"
    depends_on:
      - mongo
