services:
  mongo:
    container_name: mongo-payment
    image: mongo:latest
    restart: always
    ports:
      - "27021:27017"
      
  goapp:
    build: .
    container_name: goapp-payment
    env_file:
      - .env
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
