name: User Service CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'  # Use the Go version you need

      - name: Install dependencies
        run: |
          cd user-service
          go mod tidy

      - name: Run tests
        run: |
          cd user-service
          go test ./...

      - name: Build
        run: |
          cd user-service
          go build -o user-service .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          cd user-service
          docker build -t harshjosh361/user-service:latest .

      - name: Push Docker image
        run: |
          docker push harshjosh361/user-service:latest 
