version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
      
  goapp:
    build: .
    container_name: goapp
    ports:
      - "8080:8080"
    depends_on:
      - mongo
