name: CD Pipeline for Multiple Services

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - user-service
          - product-service
          - payment-service
          - order-service
          - notification-service
          - cart-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.service }}  # Change the context for each service
          file: ./${{ matrix.service }}/Dockerfile  # Path to the Dockerfile for each service
          push: true
          tags: harshjosh361/${{ matrix.service }}:latest  

      - name: Notify Deployment Success
        run: echo "Docker image for ${{ matrix.service }} has been successfully deployed!"
